# Generated by Django 3.0.1 on 2020-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200122_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='from_place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='to_place',
            field=models.TextField(),
        ),
    ]
