# Generated by Django 3.0.1 on 2020-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200122_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='token',
        ),
        migrations.AddField(
            model_name='ticket',
            name='token_dzieci',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='token_szybki',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='token_ulgowy',
            field=models.IntegerField(default=0),
        ),
    ]
