# Generated by Django 3.0.1 on 2020-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20200122_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='token_dzieci',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token_szybki',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token_ulgowy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
