# Generated by Django 3.0.2 on 2020-01-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_token_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='token_price',
            new_name='token_dzieci_price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='token_szybi_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='token_ulgowy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
    ]
