# Generated by Django 3.0.2 on 2020-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20200124_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='token_dzieci_price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token_szybki_price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token_ulgowy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
