# Generated by Django 3.0.2 on 2020-01-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20200124_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='token_dzieci',
            new_name='ticket_dzieci',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='token_dzieci_price',
            new_name='ticket_dzieci_price',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='token_szybki',
            new_name='ticket_szybki',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='token_szybki_price',
            new_name='ticket_szybki_price',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='token_ulgowy',
            new_name='ticket_ulgowy',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='token_ulgowy_price',
            new_name='ticket_ulgowy_price',
        ),
    ]
